services:
  postgres:
    image: postgres:16-alpine
    environment:
      - DATABASE_URL=postgresql+asyncpg://employee_user:employee_password@postgres:5432/employee_db

      - JWT_AUDIENCE=hrms-services
      - JWT_ISSUER=hrms-auth-service
      - AUTH_SERVICE_URL=http://localhost:8000
      - EVENT_BUS_URL=nats://nats:4222
      - DEBUG=True
      - LOG_LEVEL=INFO
      - SERVICE_PORT=8001
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - hrms-network

volumes:
  postgres_data:

networks:
  hrms-network:
    external: true